version: "3.9"
services:
  database:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "80:5432"
  front:
    build:
      context: ./dashboard-client
    ports:
      - "3000:3000"
  back:
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PORT=8080
    build:
      context: ./dashboard-server
    ports:
      - "8080:8080"